spring.datasource.url=jdbc:mysql://localhost:3306/expense_tracker_db
spring.datasource.username=sanjeet
spring.datasource.password=password123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=sanjeet_expense_tracker_super_secret_key_2024_very_long
jwt.expiration=86400000

server.port=8080